// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNYWC6VrxTrMuA3jRGmxo9PFDChzNjfiM',
    appId: '1:248196531047:web:76c6521f86680461db65c2',
    messagingSenderId: '248196531047',
    projectId: 'finalhabit',
    authDomain: 'finalhabit.firebaseapp.com',
    storageBucket: 'finalhabit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJ5YtlVV8R8SC4uug2AsLGR9m2DNRQDk',
    appId: '1:248196531047:android:03dcdbed70fc4f92db65c2',
    messagingSenderId: '248196531047',
    projectId: 'finalhabit',
    storageBucket: 'finalhabit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt08c4qvz4lq31YSF5PWI-jRLsRQcOPv0',
    appId: '1:248196531047:ios:074f75d597918b54db65c2',
    messagingSenderId: '248196531047',
    projectId: 'finalhabit',
    storageBucket: 'finalhabit.firebasestorage.app',
    iosBundleId: 'com.test.habitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt08c4qvz4lq31YSF5PWI-jRLsRQcOPv0',
    appId: '1:248196531047:ios:074f75d597918b54db65c2',
    messagingSenderId: '248196531047',
    projectId: 'finalhabit',
    storageBucket: 'finalhabit.firebasestorage.app',
    iosBundleId: 'com.test.habitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNYWC6VrxTrMuA3jRGmxo9PFDChzNjfiM',
    appId: '1:248196531047:web:768aece23786055cdb65c2',
    messagingSenderId: '248196531047',
    projectId: 'finalhabit',
    authDomain: 'finalhabit.firebaseapp.com',
    storageBucket: 'finalhabit.firebasestorage.app',
  );
}
